#!/usr/bin/env node

var async = require('async')
  , fs = require('fs')
  , mustache = require('mustache')
  , request = require('request')
  , yargs = require('yargs');

var environment = yargs.argv._[0];
var environmentPath = 'environments/' + environment + '/';
var configString = fs.readFileSync(environmentPath + 'config.json', 'utf8');
var config = JSON.parse(configString);

configString = mustache.render(configString, config);
config = JSON.parse(configString);

console.dir(config);

var buildCreateClusterScript = function(config) {
    var scriptTemplate = fs.readFileSync('environments/common/create-cluster.sh', 'utf8');

    var createScript = mustache.render(scriptTemplate, config);

    var createClusterPath = environmentPath + 'create-cluster.sh';

    fs.writeFileSync(createClusterPath, createScript);
    fs.chmodSync(createClusterPath, 0755);    
};

var buildConfigEnvironmentScript = function(config) {
    var scriptTemplate = fs.readFileSync('environments/common/config-env.sh', 'utf8');

    var createScript = mustache.render(scriptTemplate, config);

    var createClusterPath = environmentPath + 'config-env.sh';

    fs.writeFileSync(createClusterPath, createScript);
    fs.chmodSync(createClusterPath, 0755);    
};

var buildInstallScript = function(config) {
    var scriptTemplate = fs.readFileSync('environments/common/install.sh', 'utf8');

    var createScript = mustache.render(scriptTemplate, config);

    var createClusterPath = environmentPath + 'install.sh';

    fs.writeFileSync(createClusterPath, createScript);
    fs.chmodSync(createClusterPath, 0755);
};

buildCreateClusterScript(config);
buildConfigEnvironmentScript(config);
buildInstallScript(config);