#!/bin/bash
cd ubuntu
./build-container
./push-container

cd ../nodejs
./build-container
./push-container

cd ../consumption
./build-container
./push-container

cd ../registry
./build-container
./push-container

cd ../ingestion
./build-container
./push-container

cd ../frontdoor
./build-container
./push-container
