#! /bin/sh
# /etc/init.d/noip

### BEGIN INIT INFO
# Provides:          nitrogen
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start nitrogen at boot.
# Description:       Start nitrogen at boot.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting nitrogen"
    cd /var/www/api && nohup ./n2 > /dev/null 2>&1 &
    ;;
  stop)
    echo "Stopping nitrogen"
    killall node
    ;;
  *)
    echo "Usage: /etc/init.d/nitrogen {start|stop}"
    exit 1
    ;;
esac

exit 0